build

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -3,10 +3,19 @@ name: Pull-Request-Checks
 
 on: [push]
 
-jobs:
+env:
+  REGISTRY: 353146681200.dkr.ecr.us-east-1.amazonaws.com/otterize
+  REPOSITORY_NAME: otterize
 
-  test:
+jobs:
+  build:
+    name: Build
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        service:
+          - intents-operator
+          - watcher
 
     steps:
       - name: Check out the code
@@ -14,5 +23,73 @@ jobs:
         with:
           fetch-depth: 1
 
-      - name: Test build
-        run: cd src && VERSION=test make docker-build
+      - name: Set up Docker Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@master
+        with:
+          driver-opts: network=host
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v1
+        with:
+          username: otterize
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      # Registry login step intentionally missing
+
+      - name: Build & Test
+        uses: docker/build-push-action@v2
+        with:
+          context: src/
+          file: src/${{ matrix.service }}.Dockerfile
+          tags: ${{ env.REGISTRY }}:${{ matrix.service }}-${{ github.sha }}
+          push: true
+          target: release
+          network: host
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          build-args: RUN_ID=${{ github.run_id }}
+          secrets: |
+            "github_token=${{ secrets.OTTERIZEBOT_GITHUB_TOKEN }}"
+
+  tag-latest:
+    name: Tag latest
+    if: github.ref == 'refs/heads/main'
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+
+      - id: install-aws-cli
+        uses: unfor19/install-aws-cli-action@v1
+
+      # Push the Docker image to AWS ECR
+      - name: Tag Images as latest
+        run: |-
+          retag_image_as_latest() { MANIFEST=$(aws ecr batch-get-image --repository-name ${{ env.REPOSITORY_NAME }} --image-ids imageTag="$1-${{ github.sha }}" --query "images[].imageManifest" --output text); if [ -z "$MANIFEST" ]; then echo Manifest not found; exit 1; fi; OUTPUT=$(aws ecr put-image --repository-name ${{ env.REPOSITORY_NAME }} --image-tag "$1-latest" --image-manifest "$MANIFEST" 2>&1 || true); if echo $OUTPUT | grep 'An error occurred' >/dev/null && ! echo $OUTPUT | grep ImageAlreadyExistsException >/dev/null; then echo $OUTPUT; exit 1; fi; }
+          retag_image_as_latest intents-operator
+          retag_image_as_latest watcher
